- name: Ensure tags are present on a EC2 "{{ item }}"
  amazon.aws.ec2_tag:
    region: "{{ region }}"                                 
    resource: "{{ item }}"                              #The EC2 resource id.
    state: "{{ state }}"                                 
    tags:
      Name: "{{ ec2_tags.Name }}"                           #key: value
      Location: "{{ tags.Location }}"
      Environment: "{{ tags.Environment }}"
  tags: ec2