---

#Common Variables
state: present                                       #present(default) to create , absent to remove tags
region: us-west-2                                    #The AWS region to use.
tags:                                                #Common Tags for all the resources
  # Name: xxxx
  Location: us-west-2
  Environment: production


# vars file for aws-ec2-tag
state: present                                       #present(default) to create , absent to remove tags
ec2_tags:                                            #key: value for Name Tag
  Name: foo-bar       
instance_id:                                         #The EC2 resource id.
    - i-xxxxxxxxxxxxxxxxxx


# vars file for aws-vpc-subnet-tag
vpc_tags:                                             #key: value for Name Tag
  Name: foo-bar       
vpc_id:                                               #The VPC resource id.
   - vpc-xxxxxxxxxxxxxxxxxx

# vars for aws-subnet
public_subnet_id:
    - subnet-xxxxxxxxxxxxxxxxxx
    - subnet-xxxxxxxxxxxxxxxxxx

public_subnet_tags:
    Name: public-subnet-myvpc

private_subnet_id:
    - subnet-xxxxxxxxxxxxxxxxxx 
    - subnet-xxxxxxxxxxxxxxxxxx
private_subnet_tags:
    Name: private-subnet-myvpc

# vars file for aws-ELB-tag
# Define Classic Loadbalancer names, tags
classic_elb_name:                                    #The CLB resource name.
  - myclb

classic_elb_tags:                                    #key: value for Name Tag
    Name: foo-clb    

# Define Application Loadbalancer names, tags
application_elb_name:                                #The ALB resource name.
  - myalb

application_elb_tags:
    Name: foo-alb


# Define Network Loadbalancer names, tags
network_elb_name:                                #The NLB resource name.
  - mynlb

network_elb_tags:
    Name: foo-nlb

# Vars for target groups
tg_name:                                             #Target Groups Name
  - mytargetgroup

tg_tags:                                             #Target Groups Tags
    Name: foo-tg

# Vars for Elastic IP
public_ip:                                           #Public IP of the EIP
  - 1.2.3.4

eip_tags:                                            #Tags added to the EIP of the Public IP
    Name: foo-eip
      
# vars for security groups
purge_tags: false
group_id:                                            #Security Group IDs
 - sg-xxxxxxxxxxxxxxxxxx

sg_tags:                                              #Security Group Name Tag
    Name: foo-sg

#vars for rds
purge_tags: false
db_instance_identifier:                               #db identifier of AWS RDS
 - database-1
 - database-2
rds_tags:                                             #RDS Name Tag
     Name: foo-rds

